<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="FalconXtreme" name="Regression suite 1" tests="10" failures="1" timestamp="28 Sep 2016 15:42:14 GMT" time="17.361" errors="0">
  <testcase name="setData" time="0.005" classname="com.guru.test.DataProviderExample"/>
  <testcase name="setData" time="0.001" classname="com.guru.test.DataProviderExample"/>
  <testcase name="setData" time="0.001" classname="com.guru.test.DataProviderExample"/>
  <testcase name="testCaseEnabling" time="0.002" classname="com.guru.test.ExceptionExample">
    <failure type="java.lang.AssertionError" message="failed!!!!! expected [test1] but found [test]">
      <![CDATA[java.lang.AssertionError: failed!!!!! expected [test1] but found [test]
	at com.guru.test.ExceptionExample.testCaseEnabling(ExceptionExample.java:12)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCaseEnabling -->
  <testcase name="testMethod" time="3.281" classname="com.guru.test.ParameterDataproviderWithClassLevel"/>
  <testcase name="testMethod" time="3.171" classname="com.guru.test.ParameterDataproviderWithClassLevel"/>
  <testcase name="testMethod" time="3.178" classname="com.guru.test.ParameterDataproviderWithClassLevel"/>
  <testcase name="testCase01" time="0.001" classname="com.guru.test.TestNFExample"/>
  <testcase name="testCase02" time="0.002" classname="com.guru.test.TestNFExample"/>
  <testcase name="testCase03" time="0.002" classname="com.guru.test.TestNFExample"/>
</testsuite> <!-- Regression suite 1 -->
